### PR TITLE
added language selector for site name variable

### PR DESCRIPTION
**Pull request by beaubbe**

### CODE REVIEW

**Comment by nitriques** [comment]
Could we use this instead ?

```xsl
<xsl:choose>
   <xsl:when test="string-length($config/site-titre/item[@lang=$url-language]) != 0">
      <xsl:value-of select="$config/site-titre/item[@lang=$url-language]" />
   </xsl:when>
   <xsl:otherwise>
      <xsl:value-of select="$config/site-titre" />
   </xsl:otherwise>
</xsl:choose>
```

**Comment by beaubbe** [comment]
Good thinking :clap: . like this the variable will always wirk. You should add it. :metal:

**Comment by nitriques** [comment]
I would :heart: if you could do it please :exclamation: :kiss: :feet:

**Comment by nitriques** [comment]
Closed with c654b708092206c5f6b0e907ec722d91ab90ba97

**Pull request closed without merging**
